### ISSUE TITLE
非常棒的分享！以及一点小建议

### ISSUE THREAD

**Issue by cycleuser** [Geokeke/Daily-Happiness-Record#8]
话说如果有兴趣的话，建议尝试一下 Pelican 或者 Hexo + Github Pages制作个人站点，很简单有趣。

另外文本更新内容也可以考虑一下使用最新的在上面，由上而下从新到旧这样排列，阅读的时候会有不同体验。

**Comment by Geokeke** [comment]
非常感谢你的建议！做这个主要是尝试一下Github 的操作和功能，也没有坚持写下来。浏览了你用 Pelican 制作的个人站点，感觉很棒。
